tasks:
  - init: |
      rm -rf .git
      rm ./README.MD
      rm .gitpod.yml
      python3 -m pip install -U pip poetry
      sudo apt install -y ffmpeg
      sudo apt install -y libopus-dev

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - oderwat.indent-rainbow
    - usernamehw.errorlens
