tasks:
  - init: |
      rm -rf .git
      rm ./README.MD
      rm .gitpod.yml
      python -m venv venv
      source venv/bin/activate
      python -m pip install -U pip poetry 

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - oderwat.indent-rainbow
    - usernamehw.errorlens
